import type { Metadata } from 'next';
import { Tinos } from 'next/font/google';
import Navbar from '@/component/common/Navbar';
import ReduxProvider from '@/libs/ReduxProvider';
import Footer from '@/component/common/Footer';
import MessagePopUp from '@/component/popup/MessagePopUp';
import './globals.css';

const Tinosfont = Tinos({
  weight: ['400', '700'],
  style: 'normal',
  preload: true,
  adjustFontFallback: true,
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${Tinosfont.className} antialiased`}>
        <ReduxProvider>
          <Navbar />
          <MessagePopUp />
          {children}
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
